# Generated by Django 2.0.3 on 2018-04-01 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
