# Generated by Django 2.0.3 on 2018-04-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180401_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='fire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
